M48
; DRILL file {KiCad 8.0.4-8.0.4-0~ubuntu22.04.1} date 2024-08-18T15:20:46-0700
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2024-08-18T15:20:46-07:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.4-8.0.4-0~ubuntu22.04.1
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0984
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.1000
%
G90
G05
T1
X9.944Y-5.069
X9.944Y-5.769
T2
X9.944Y-5.769
M30
